[package]
name = "OpenGLSandbox"
version = "0.1.0"
authors = ["Aakash Sham <aakash.sham@gmail.com>"]

[dependencies]
gl = "0.10.0"

[dependencies.sdl2]
version = "0.31.0"
features = ["bundled", "static-link"]
